
services:
  worker: &netbox
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "python manage.py rqworker"
    env_file: ./env/netbox.env
    depends_on:
      netbox:
        condition: service_healthy
    volumes:
      - ./configuration/configuration.py:/opt/netbox/netbox/netbox/configuration.py
      - ./plugins/:/plugins/
  netbox:
    <<: *netbox
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    healthcheck:
      test: curl -f http://localhost:8000/login/ || exit 1
      start_period: 90s
      timeout: 3s
      interval: 15s
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14-alpine
    env_file: ./env/postgres.env
    volumes:
      - pgdata-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: sh -c "redis-server --appendonly yes --requirepass redis"
    env_file: ./env/redis.env
    volumes:
      - redis-data:/data

volumes:
  pgdata-data:
    driver: local
  redis-data:
    driver: local #   driver: local
